<?xml version="1.0"?>
<package format="2">

  <name>stereo_slam</name>
  <version>1.1.0</version>

  <description>Stereo Slam</description>

  <url type="website">https://github.com/srv/stereo_slam</url>
  <url type="bugtracker">https://github.com/srv/stereo_slam/issues</url>
  
  <author email="pl.negre@uib.cat">Pep Lluis Negre</author>
  <maintainer email="bo-miquel.nordfeldt@uib.es">Bo Miquel Nordfeldt-Fiol</maintainer>
  
  <license>BSD-4-Clause</license>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- System Dependencies -->
  <depend>eigen</depend> 
  <depend>libsuitesparse-dev</depend>

  <!-- ROS Dependencies (Build + Exec) -->
  <depend>tf2</depend>
  <depend>roscpp</depend>
  <depend>libg2o</depend>
  <depend>tf2_ros</depend>
  <depend>pcl_ros</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>image_geometry</depend>
  <depend>image_transport</depend>
  <depend>message_filters</depend>
  <depend>tf2_geometry_msgs</depend>

  <!-- Only Build -->
  <build_depend>cmake_modules</build_depend>
  <build_depend>message_generation</build_depend>

  <!-- Only Exec -->
  <exec_depend>message_runtime</exec_depend>

</package>
